services:
  taskflow-api:
    build: .
    container_name: taskflow_api
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - taskflow-postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  taskflow-postgres:
    image: postgres:16
    container_name: taskflow_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskflow_db
    ports:
      - "5432:5432"
    volumes:
      - taskflow_pgdata:/var/lib/postgresql/data

volumes:
  taskflow_pgdata:
